/**
 * 参与方清单卡片 / 表单 / 搜索 / 分类 文案 —— 集中收口点。
 *
 * 卡片、面板、表单等 `features/map/**` 模块只 import 这里；不得为取文案而 import
 * `map-copy.ts`（那是地图组件/页面图例级文案）。中文文案全部收口于此（注释除外）。
 */
export const PARTICIPANT_COPY = {
  // ── 面板（参与方清单卡片） ──
  panelTitle: '参与方清单',
  panelHint: '按分类分区浏览，支持搜索与筛选，点击卡片联动地图',
  panelHintReadonly: '只读视图 · 写接口未启用',
  addParticipant: '添加参与方',
  searchPlaceholder: '搜索参与方名称 / 地点 / 国家',
  filterCategoryLabel: '分类',
  filterCategoryPlaceholder: '全部分类',
  empty: '暂无',
  uncategorizedTitle: '未分类',
  samePointBadge: (count: number) => `${count} 个同点`,
  collapse: '收起',
  // category* —— 分类标签（CATEGORY_META 引用于此，保证文案单一收口）
  categoryOperator: '运营商',
  categoryEquipmentVendor: '设备商',
  categoryIntegrator: '集成商',
  categoryItVendor: 'IT 厂商',
  categoryCloudVendor: '云厂商',
  categoryResearch: '研究机构',
  categoryOther: '未分类',
  // ── 卡片 ──
  manualBadge: '人工',
  selectAria: (name: string) => `定位 ${name} 到地图`,
  editAria: (name: string) => `编辑 ${name}`,
  deleteAria: (name: string) => `删除 ${name}`,
  homepageAria: (name: string) => `${name} 官网`,
  deleteConfirm: '确认删除该参与方？删除后可在重建内置种子时恢复。',
  // ── 表单 ──
  formTitleAdd: '添加参与方',
  formTitleEdit: '编辑参与方',
  formDescriptionAdd: '填写字段后保存；可从地图取点，或选择已有参与方预填（覆盖）',
  formDescriptionEdit: '保存将覆盖该参与方；内置种子会被转为「人工」条目',
  save: '保存',
  saving: '保存中…',
  cancel: '取消',
  fieldLabel: '名称',
  fieldLabelPlaceholder: '如 Alicloud',
  fieldCategory: '分类',
  fieldCountryName: '国家/地区名',
  fieldCountryCode: '国家代码',
  fieldCountryCodeHint: '两位大写 ISO 代码，如 CN',
  fieldLongitude: '经度',
  fieldLatitude: '纬度',
  fieldLocationLabel: '地点描述',
  fieldHomepageUrl: '官网',
  fieldLogoUrl: 'Logo URL',
  fieldDescription: '简介',
  fieldMarkerId: 'markerId',
  fieldMarkerIdHint: '新增时可编辑；由名称自动生成 kebab-case',
  pickFromMap: '在地图上取点',
  pickFromMapActive: '点击地图取点中，点击地图任意处回填经纬度',
  mapPickAria: '取点地图',
  selectExisting: '从已有参与方选择',
  selectExistingPlaceholder: '选择后预填并覆盖该条目',
  selectExistingHint: '用于修改内置种子：按该条目覆盖提交，避免产生重复标记',
  adminToken: '管理员令牌',
  adminTokenPlaceholder: '输入后仅存本页会话（sessionStorage）',
  // 校验
  vLabelRequired: '请填写名称',
  vLabelTooLong: '名称不能超过 80 个字符',
  vCountryNameRequired: '请填写国家/地区名',
  vCountryNameTooLong: '国家/地区名不能超过 64 个字符',
  vCountryCodeRequired: '请填写国家代码',
  vCountryCodeFormat: '国家代码须为两位大写字母（如 CN）',
  vLongitudeRequired: '请填写经度',
  vLongitudeRange: '经度须在 -180 到 180 之间',
  vLatitudeRequired: '请填写纬度',
  vLatitudeRange: '纬度须在 -90 到 90 之间',
  vHomepageInvalid: '官网须以 http(s):// 开头',
  vLogoInvalid: 'Logo URL 须为空、http(s):// 或 / 开头',
  vMarkerIdRequired: '请填写 markerId',
  vMarkerIdFormat: 'markerId 须为小写字母/数字开头的 kebab-case',
  // 服务端错误
  errAdminToken: '管理员令牌无效',
  errWriteDisabled: '写入未启用，请联系运维',
  errField: '字段校验失败',
  errDefault: '操作失败',
} as const;