/** 每个数据文件对应一个仓储实例（见 03 文档 5.2） */
export const HOME_REPOSITORY = Symbol('HOME_REPOSITORY');
export const ORGANIZATIONS_REPOSITORY = Symbol('ORGANIZATIONS_REPOSITORY');
export const CONTRIBUTIONS_REPOSITORY = Symbol('CONTRIBUTIONS_REPOSITORY');
export const INSIGHTS_REPOSITORY = Symbol('INSIGHTS_REPOSITORY');
export const CONTRIBUTORS_REPOSITORY = Symbol('CONTRIBUTORS_REPOSITORY');
export const SUMMITS_REPOSITORY = Symbol('SUMMITS_REPOSITORY');
export const MEETINGS_REPOSITORY = Symbol('MEETINGS_REPOSITORY');

export const ALL_REPOSITORY_TOKENS = [
  HOME_REPOSITORY,
  ORGANIZATIONS_REPOSITORY,
  CONTRIBUTIONS_REPOSITORY,
  INSIGHTS_REPOSITORY,
  CONTRIBUTORS_REPOSITORY,
  SUMMITS_REPOSITORY,
  MEETINGS_REPOSITORY,
] as const;
